// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: interview_session.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createInterviewSession = `-- name: CreateInterviewSession :one
INSERT INTO interview_session(
  id,
  created_at,
  updated_at,
  user_id,
  job_id
)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, status, created_at, updated_at, user_id, job_id, transcript, user_feedbacks, hints_used, submitted_code
`

type CreateInterviewSessionParams struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	JobID     uuid.UUID
}

func (q *Queries) CreateInterviewSession(ctx context.Context, arg CreateInterviewSessionParams) (InterviewSession, error) {
	row := q.db.QueryRowContext(ctx, createInterviewSession,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.UserID,
		arg.JobID,
	)
	var i InterviewSession
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.JobID,
		&i.Transcript,
		&i.UserFeedbacks,
		&i.HintsUsed,
		&i.SubmittedCode,
	)
	return i, err
}
