// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: interview_session.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createInterviewSession = `-- name: CreateInterviewSession :one
INSERT INTO interview_session(
  id,
  created_at,
  updated_at,
  user_id,
  job_id
)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, status, created_at, updated_at, user_id, job_id, transcript, user_feedbacks, hints_used, submitted_code
`

type CreateInterviewSessionParams struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	JobID     uuid.UUID
}

func (q *Queries) CreateInterviewSession(ctx context.Context, arg CreateInterviewSessionParams) (InterviewSession, error) {
	row := q.db.QueryRowContext(ctx, createInterviewSession,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.UserID,
		arg.JobID,
	)
	var i InterviewSession
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.JobID,
		&i.Transcript,
		&i.UserFeedbacks,
		&i.HintsUsed,
		&i.SubmittedCode,
	)
	return i, err
}

const getCompleteSessionsByUserID = `-- name: GetCompleteSessionsByUserID :many
SELECT id, status, created_at, updated_at, user_id, job_id, transcript, user_feedbacks, hints_used, submitted_code
FROM interview_session
WHERE user_id = $1
AND status = 'completed'
ORDER BY updated_at DESC
`

func (q *Queries) GetCompleteSessionsByUserID(ctx context.Context, userID uuid.UUID) ([]InterviewSession, error) {
	rows, err := q.db.QueryContext(ctx, getCompleteSessionsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InterviewSession
	for rows.Next() {
		var i InterviewSession
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.JobID,
			&i.Transcript,
			&i.UserFeedbacks,
			&i.HintsUsed,
			&i.SubmittedCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInterviewSession = `-- name: UpdateInterviewSession :one
UPDATE interview_session
SET
  status = $2,
  transcript = $3,
  user_feedbacks = $4,
  hints_used = $5,
  submitted_code = $6,
  updated_at = NOW()
WHERE id = $1
RETURNING id, status, created_at, updated_at, user_id, job_id, transcript, user_feedbacks, hints_used, submitted_code
`

type UpdateInterviewSessionParams struct {
	ID            uuid.UUID
	Status        InterviewStatus
	Transcript    pqtype.NullRawMessage
	UserFeedbacks pqtype.NullRawMessage
	HintsUsed     pqtype.NullRawMessage
	SubmittedCode pqtype.NullRawMessage
}

func (q *Queries) UpdateInterviewSession(ctx context.Context, arg UpdateInterviewSessionParams) (InterviewSession, error) {
	row := q.db.QueryRowContext(ctx, updateInterviewSession,
		arg.ID,
		arg.Status,
		arg.Transcript,
		arg.UserFeedbacks,
		arg.HintsUsed,
		arg.SubmittedCode,
	)
	var i InterviewSession
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.JobID,
		&i.Transcript,
		&i.UserFeedbacks,
		&i.HintsUsed,
		&i.SubmittedCode,
	)
	return i, err
}
