// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type CompanyProfile struct {
	UserID             uuid.UUID
	CompanyName        string
	CompanyWebsite     string
	CompanyDescription string
}

type Job struct {
	ID              uuid.UUID
	CreatedAt       time.Time
	UpdatedAt       time.Time
	CompanyName     string
	Title           string
	Description     string
	Languages       []string
	CreatedBy       uuid.UUID
	CustomInterview bool
}

type User struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Username  string
	Password  string
	Email     string
	Role      string
}

type UserProfile struct {
	UserID       uuid.UUID
	ResumePath   sql.NullString
	ParsedResume sql.NullString
}
