// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createCompanyProfile = `-- name: CreateCompanyProfile :one
INSERT INTO company_profiles (
  user_id,
  company_name,
  company_website,
  company_description
)
VALUES ($1, $2, $3, $4)
RETURNING user_id, company_name, company_website, company_description
`

type CreateCompanyProfileParams struct {
	UserID             uuid.UUID
	CompanyName        string
	CompanyWebsite     string
	CompanyDescription string
}

func (q *Queries) CreateCompanyProfile(ctx context.Context, arg CreateCompanyProfileParams) (CompanyProfile, error) {
	row := q.db.QueryRowContext(ctx, createCompanyProfile,
		arg.UserID,
		arg.CompanyName,
		arg.CompanyWebsite,
		arg.CompanyDescription,
	)
	var i CompanyProfile
	err := row.Scan(
		&i.UserID,
		&i.CompanyName,
		&i.CompanyWebsite,
		&i.CompanyDescription,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  id,
  created_at,
  updated_at,
  username,
  password,
  email,
  role
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, created_at, updated_at, username, password, email, role
`

type CreateUserParams struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Username  string
	Password  string
	Email     string
	Role      string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Username,
		arg.Password,
		arg.Email,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.Password,
		&i.Email,
		&i.Role,
	)
	return i, err
}

const createUserProfile = `-- name: CreateUserProfile :one
INSERT INTO user_profiles (
  user_id,
  resume_path,
  parsed_resume
)
VALUES ($1, $2, $3)
RETURNING user_id, resume_path, parsed_resume
`

type CreateUserProfileParams struct {
	UserID       uuid.UUID
	ResumePath   sql.NullString
	ParsedResume sql.NullString
}

func (q *Queries) CreateUserProfile(ctx context.Context, arg CreateUserProfileParams) (UserProfile, error) {
	row := q.db.QueryRowContext(ctx, createUserProfile, arg.UserID, arg.ResumePath, arg.ParsedResume)
	var i UserProfile
	err := row.Scan(&i.UserID, &i.ResumePath, &i.ParsedResume)
	return i, err
}

const getCompanyProfileByID = `-- name: GetCompanyProfileByID :one
SELECT user_id, company_name, company_website, company_description FROM company_profiles WHERE user_id = $1
`

func (q *Queries) GetCompanyProfileByID(ctx context.Context, userID uuid.UUID) (CompanyProfile, error) {
	row := q.db.QueryRowContext(ctx, getCompanyProfileByID, userID)
	var i CompanyProfile
	err := row.Scan(
		&i.UserID,
		&i.CompanyName,
		&i.CompanyWebsite,
		&i.CompanyDescription,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, created_at, updated_at, username, password, email, role FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.Password,
		&i.Email,
		&i.Role,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, created_at, updated_at, username, password, email, role FROM users WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.Password,
		&i.Email,
		&i.Role,
	)
	return i, err
}

const getUserProfileByID = `-- name: GetUserProfileByID :one
SELECT user_id, resume_path, parsed_resume FROM user_profiles WHERE user_id = $1
`

func (q *Queries) GetUserProfileByID(ctx context.Context, userID uuid.UUID) (UserProfile, error) {
	row := q.db.QueryRowContext(ctx, getUserProfileByID, userID)
	var i UserProfile
	err := row.Scan(&i.UserID, &i.ResumePath, &i.ParsedResume)
	return i, err
}
